
[SectionHeader6]
Meter=String
Text=[#SH6]
X=30
Y=20R
FontFace=Quicksand Medium
FontSize=14
FontColor=#FontColor1#
StringAlign=LeftTop
InlineSetting=Weight | 700
AntiAlias=1
ClipString=1
Container=OptionContainer

[Skin]
Meter=String
Text=[#skinName]
X=30
Y=10R
FontFace=Quicksand Medium
FontSize=18
FontColor=#Pink1#
StringAlign=LeftTop
AntiAlias=1
ClipString=1
Container=OptionContainer

[Author]
Meter=String
Text=By Bunz
X=30
Y=3R
FontFace=Quicksand Medium
FontSize=12
FontColor=#Pink2#
StringAlign=LeftTop
AntiAlias=1
ClipString=1
Container=OptionContainer

[Version]
Meter=String
Text=[#AVrs] [#Version]
X=30
Y=5R
FontFace=Nunito
FontSize=10
FontColor=#FontColor1#
StringAlign=LeftTop
AntiAlias=1
ClipString=1
Container=OptionContainer

[Description]
Meter=String
Text=[#ADsc]
X=30
Y=5R
W=290
FontFace=Nunito
FontSize=9
FontColor=#FontColor1#
StringAlign=LeftTop
AntiAlias=1
ClipString=2
Container=OptionContainer

[Warning]
Meter=String
Text=[#AWrng]
X=30
Y=3R
W=290
FontFace=Nunito
FontSize=9
FontColor=#Red#
StringAlign=LeftTop
AntiAlias=1
ClipString=2
Container=OptionContainer
