
[AboutHeader]
Meter=String
Text=[#S5H]
X=30
Y=20R
FontFace=Quicksand Medium
FontSize=14
FontColor=eeeeee
StringAlign=LeftTop
InlineSetting=Weight | 700
AntiAlias=1
ClipString=1
Container=OptionContainer

[Skin]
Meter=String
Text=[#skinName]
X=30
Y=10R
FontFace=Quicksand Medium
FontSize=18
FontColor=EB2CF8
StringAlign=LeftTop
AntiAlias=1
ClipString=1
Container=OptionContainer

[Author]
Meter=String
Text=By Bunz
X=30
Y=3R
FontFace=Quicksand Medium
FontSize=12
FontColor=b719c2
StringAlign=LeftTop
AntiAlias=1
ClipString=1
Container=OptionContainer

[Version]
Meter=String
Text=[#S5Vrs] [#Version]
X=30
Y=5R
FontFace=Nunito
FontSize=10
FontColor=eeeeee
StringAlign=LeftTop
AntiAlias=1
ClipString=1
Container=OptionContainer

[Description]
Meter=String
Text=[#S5Dsc]
X=30
Y=5R
W=290
FontFace=Nunito
FontSize=9
FontColor=eeeeee
StringAlign=LeftTop
AntiAlias=1
ClipString=2
Container=OptionContainer

[Warning]
Meter=String
Text=[#S5Wrng]
X=30
Y=3R
W=290
FontFace=Nunito
FontSize=9
FontColor=eb4034
StringAlign=LeftTop
AntiAlias=1
ClipString=2
Container=OptionContainer
